### PR TITLE
Add Mastodon link

### PR DESCRIPTION
**Pull request by bhollis**
@liminalAce would you be able to make a new Mastodon logo image?

### CODE REVIEW

**Comment by lowPolySkeleton** [comment]
Yeah I can make one

**Comment by bhollis** [comment]
@liminalAce gentlest ping :-). If you have a link to whatever your originals are I can put it together too (or redraw).

**Comment by lowPolySkeleton** [comment]
yeah sorry, things. I can;t find the original ai files, so I'm going to remake them all to make sure they all match. I'll pull this and make the changes asap.

**Comment by lowPolySkeleton** [comment]
okay I remade the icons, and added the mastodon one. Had to adjust some css as well since I made them flat grey instead of transparent white.

**Comment by delphiactual** [comment]
don't forget to run `yarn i18n` to apply the updates from the template to the locale pages.

**Comment by bhollis** [comment]
Awesome, thanks!

**Pull request merged**
